### ISSUE TITLE
Explore feed search function and pagination

### ISSUE THREAD

**Issue by PSheon** [wired-labs/wired#662]
The explore feed is on-chain data so we can only filter in the client-side temporary for now?
I think the better way is run a contract event listener and update to the backend. maybe we can build it later.

<img width="1488" alt="截圖 2023-03-07 下午3 24 11" src="https://user-images.githubusercontent.com/20603727/223353793-11851582-a3d6-446c-a14d-dcca2cc3968e.png">

**Comment by kayhhh** [comment]
I like it 🔥 I think filtering in the client is fine for now. As the number of spaces grows we will need a more advanced solution for filtering spaces server side, that might involve contract events but im not exactly sure at the moment how they would fit in with Nextjs 13. My first thought was to cache spaces in the database and update them with contract events, but Next 13 has
 a lot of built in caching support so it might not be needed.

Doing things server side seems like a complicated problem, should probably be its own issue.

**Comment by PSheon** [comment]
@kayhhh can we close this issue?

**Comment by kayhhh** [comment]
Yep, merged in #674
